#!/usr/bin/env node
// URL Encode
if (process.argv.length <= 2) {
  console.log('Error - requires a string argument');
  process.exit(1);
}
console.log(encodeURIComponent(process.argv.slice(2).join(' ')));
